# Generated by Django 5.1.7 on 2025-05-06 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulador_id', models.CharField(default=uuid.uuid4, max_length=36)),
                ('ronda', models.IntegerField()),
                ('y0', models.FloatField()),
                ('y1', models.FloatField()),
                ('r', models.FloatField()),
                ('rho', models.FloatField()),
                ('c0', models.FloatField(blank=True, null=True)),
                ('c1', models.FloatField(blank=True, null=True)),
                ('s', models.FloatField(blank=True, null=True)),
                ('U0', models.FloatField(blank=True, null=True)),
                ('U0_max', models.FloatField(blank=True, null=True)),
                ('percentagem', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['simulador_id', 'ronda'],
            },
        ),
        migrations.CreateModel(
            name='SimuladorI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulador_id_i', models.CharField(default=uuid.uuid4, max_length=36)),
                ('ronda', models.IntegerField()),
                ('r', models.FloatField()),
                ('A', models.FloatField()),
                ('alpha', models.FloatField()),
                ('delta', models.FloatField()),
                ('investimento', models.FloatField(blank=True, null=True)),
                ('V0', models.FloatField(blank=True, null=True)),
                ('V0_max', models.FloatField(blank=True, null=True)),
                ('percentagem', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['simulador_id_i', 'ronda'],
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveIntegerField()),
                ('nacionalidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
