# Generated by Django 5.1.7 on 2025-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='is_docente',
            field=models.BooleanField(default=False),
        ),
    ]
