# Generated by Django 5.1.7 on 2025-06-04 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_utilizador_is_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaSimulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('simulador_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tipo', models.CharField(choices=[('I', 'Simulador Escolha Intertemporal de consumo'), ('II', 'Simulador Esocolha Intertemporal de investimento')], max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='simulador',
            options={'ordering': ['instancia', 'ronda']},
        ),
        migrations.AlterModelOptions(
            name='simuladori',
            options={'ordering': ['instancia', 'ronda']},
        ),
        migrations.RemoveField(
            model_name='simulador',
            name='simulador_id',
        ),
        migrations.RemoveField(
            model_name='simuladori',
            name='simulador_id_i',
        ),
        migrations.AddField(
            model_name='simulador',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simuladori',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulador',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.instanciasimulador'),
        ),
        migrations.AddField(
            model_name='simuladori',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.instanciasimulador'),
        ),
    ]
