# Generated by Django 5.1.7 on 2025-06-20 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_utilizador_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimuladorPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('min_p1', models.FloatField()),
                ('max_p1', models.FloatField()),
                ('min_p2', models.FloatField()),
                ('max_p2', models.FloatField()),
                ('min_p3', models.FloatField()),
                ('max_p3', models.FloatField()),
                ('min_p4', models.FloatField()),
                ('max_p4', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='instanciasimulador',
            name='tipo',
            field=models.CharField(choices=[('I', 'Simulador Escolha Intertemporal de consumo'), ('II', 'Simulador Esocolha Intertemporal de investimento'), ('III', 'Simulador Personalizado')], max_length=10),
        ),
        migrations.CreateModel(
            name='SimuladorP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.IntegerField()),
                ('p1', models.FloatField()),
                ('p2', models.FloatField()),
                ('p3', models.FloatField()),
                ('p4', models.FloatField()),
                ('p5', models.FloatField()),
                ('percentagem', models.FloatField(blank=True, null=True)),
                ('valor1', models.FloatField(blank=True, null=True)),
                ('valor2', models.FloatField(blank=True, null=True)),
                ('valor3', models.FloatField(blank=True, null=True)),
                ('valor4', models.FloatField(blank=True, null=True)),
                ('instancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.instanciasimulador')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['instancia', 'ronda'],
            },
        ),
    ]
