# Generated by Django 5.1.7 on 2025-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_simuladorpconfig_alter_instanciasimulador_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuladorp',
            name='p5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
