# Generated by Django 5.1.7 on 2025-06-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_alter_simuladorp_p5'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladori',
            name='K',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simuladori',
            name='K_opt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
